import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const LANGUAGE_STORAGE_KEY = 'app-language';

const translations = {
  id: {
    'language.id': 'ID',
    'language.en': 'EN',

    'sidebar.category.general': 'UMUM',
    'sidebar.category.document': 'DOKUMEN',
    'sidebar.category.tax': 'PAJAK & KEPATUHAN',
    'sidebar.category.system': 'SISTEM',
    'sidebar.category.accounting': 'AKUNTANSI',

    'sidebar.item.dashboard': 'Dashboard',
    'sidebar.item.myJob': 'Pekerjaan',
    'sidebar.item.manualBook': 'Manual Instruksi',
    'sidebar.item.sop': 'SOP',
    'sidebar.item.filling': 'Filling',
    'sidebar.item.documents': 'Dokumen',
    'sidebar.item.anydoc': 'AnyDoc Converter',
    'sidebar.item.aiDocIntel': 'AI Document Intelligence',
    'sidebar.item.aiDocTrain': 'Training Dokumen',
    'sidebar.item.aiPdfTools': 'AI PDF Tools',
    'sidebar.item.approvals': 'Laporan Entertainment',
    'sidebar.item.entertainment': 'Entertainment',
    'sidebar.item.invoices': 'Invoices',
    'sidebar.item.forwarder': 'Forwarder',
    'sidebar.item.pdfTemplates': 'Template PDF',
    'sidebar.item.compliance': 'Kepatuhan',
    'sidebar.item.taxCalc': 'Kalkulasi Pajak',
    'sidebar.item.reporting': 'Pelaporan',
    'sidebar.item.masterData': 'Master Data',
    'sidebar.item.book': 'Book (COA)',
    'sidebar.item.systemLogs': 'Log Sistem',

    'sidebar.ocr.ready': 'OCR Siap',
    'sidebar.ocr.queueEmpty': 'Antrian kosong',
    'sidebar.ocr.processing': 'Proses OCR...',
    'sidebar.ocr.active': 'Aktif',
    'sidebar.ocr.waiting': 'Antri',
    'sidebar.ocr.ok': 'OK',
    'sidebar.ocr.fail': 'Gagal',
    'sidebar.ocr.reset': 'Reset',

    'sidebar.user.guest': 'Tamu',
    'sidebar.user.viewer': 'Viewer',
    'sidebar.search.placeholder': 'Cari menu…',
    'sidebar.search.empty': 'Tidak ada menu ditemukan',
    'sidebar.search.results': 'Hasil Pencarian',
    'sidebar.action.toggleTheme': 'Ganti Tema',
    'sidebar.action.logout': 'Keluar',

    // ── Common UI ──
    'common.previous': 'Sebelumnya',
    'common.next': 'Berikutnya',
    'common.search': 'Cari',
    'common.save': 'Simpan',
    'common.cancel': 'Batal',
    'common.delete': 'Hapus',
    'common.edit': 'Edit',
    'common.view': 'Lihat',
    'common.add': 'Tambah',
    'common.close': 'Tutup',
    'common.loading': 'Memuat...',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.yes': 'Ya',
    'common.no': 'Tidak',
    'common.confirm': 'Konfirmasi',
    'common.success': 'Berhasil',
    'common.error': 'Gagal',
    'common.warning': 'Peringatan',
    'common.noData': 'Tidak ada data',
    'common.all': 'Semua',
    'common.status': 'Status',
    'common.type': 'Tipe',
    'common.name': 'Nama',
    'common.description': 'Deskripsi',
    'common.date': 'Tanggal',
    'common.amount': 'Jumlah',
    'common.total': 'Total',
    'common.action': 'Aksi',
    'common.copy': 'Salin',
    'common.copied': 'Tersalin!',
    'common.detail': 'Detail',
    'common.back': 'Kembali',
    'common.submit': 'Kirim',
    'common.filter': 'Filter',
    'common.sort': 'Urutkan',
    'common.of': 'dari',
    'common.page': 'Halaman',
    'common.rows': 'baris',
    'common.selectAll': 'Pilih Semua',
    'common.selected': 'dipilih',
    'common.upload': 'Unggah',
    'common.download': 'Unduh',
    'common.print': 'Cetak',
    'common.copyClipboard': 'Salin ke clipboard',
    'common.preview': 'Pratinjau',
    'common.reset': 'Atur Ulang',
    'common.apply': 'Terapkan',
    'common.enabled': 'Aktif',
    'common.disabled': 'Nonaktif',
    'common.active': 'Aktif',
    'common.inactive': 'Nonaktif',

    // ── Tooltips ──
    'tooltip.exportExcel': 'Export seluruh data ke Excel',
    'tooltip.importData': 'Import data dari file Excel',
    'tooltip.downloadTemplate': 'Download template Excel untuk import',
    'tooltip.deleteEntry': 'Hapus data ini',
    'tooltip.editEntry': 'Edit data ini',
    'tooltip.viewDetail': 'Lihat detail',
    'tooltip.refresh': 'Refresh data',
    'tooltip.history': 'Lihat riwayat',
    'tooltip.shareDept': 'Bagikan ke departemen lain',
    'tooltip.downloadPdf': 'Unduh PDF asli',
    'tooltip.ocrView': 'Lihat teks hasil OCR',
    'tooltip.zoomDetail': 'Zoom Detail',
    'tooltip.usePpnCustom': 'Gunakan PPN custom',
    'tooltip.collapseGroup': 'Kolom grup: nilai ada di baris di atas baris data dan diwariskan ke baris di bawah',
    'tooltip.mapHeader': 'Map sebagai field header',
    'tooltip.tableHeader': 'Jadikan header tabel item',
    'tooltip.copyValue': 'Salin Nilai',
    'tooltip.copyTotal': 'Salin Total',
    'tooltip.renameColumn': 'Ubah Nama',
    'tooltip.deleteColumn': 'Hapus Kolom',
    'tooltip.restoreGudang': 'Restore ke Gudang',
    'tooltip.logout': 'Keluar',
    'tooltip.previous': 'Sebelumnya',
    'tooltip.next': 'Berikutnya',

    // ── Months ──
    'month.jan': 'Januari', 'month.feb': 'Februari', 'month.mar': 'Maret',
    'month.apr': 'April', 'month.may': 'Mei', 'month.jun': 'Juni',
    'month.jul': 'Juli', 'month.aug': 'Agustus', 'month.sep': 'September',
    'month.oct': 'Oktober', 'month.nov': 'November', 'month.dec': 'Desember',

    // ── Invoices ──
    'invoice.status.submitted': 'Submitted',
    'invoice.status.proforma': 'Proforma',
    'invoice.status.pending': 'Pending',
    'invoice.status.sentBack': 'Dikembalikan',
    'invoice.status.rejected': 'Ditolak',
    'invoice.status.approved': 'Disetujui',
    'invoice.status.taxRequested': 'Pajak Diminta',
    'invoice.status.tax': 'Pajak',
    'invoice.status.settled': 'Selesai',
    'invoice.status.cancelled': 'Dibatalkan',
    'invoice.stepper.submit': 'Submit',
    'invoice.stepper.proforma': 'Proforma',
    'invoice.stepper.tax': 'Pajak',
    'invoice.stepper.settle': 'Selesai',
    'invoice.searchPlaceholder': 'Cari (PO, proforma, dealer...)',
    'invoice.searchData': 'Cari data...',
    'invoice.searchInvoice': 'Cari no invoice / PO / dealer...',
    'invoice.searchDealer': 'Cari Dealer...',
    'invoice.searchModel': 'Cari Model...',
    'invoice.placeNPWP': 'NPWP (16 digit)',
    'invoice.placeDealerName': 'Nama Dealer',
    'invoice.placeAddress': 'Alamat',
    'invoice.placeModel': 'Model / Kode Barang',
    'invoice.placeItemDesc': 'Item Description',
    'invoice.placePrice': 'Harga',
    'invoice.placeExample': 'Contoh: Approval Akunting',
    'invoice.placeEmail': 'Ketik email, pisahkan dengan koma / enter. Contoh: akunting@perusahaan.com',
    'invoice.placeNoInvoice': 'No. Invoice',
    'invoice.exportAll': 'Export seluruh data invoice ke Excel',
    'invoice.usePpnCustom': 'Gunakan PPN custom',
    'invoice.errorUpload': 'Error saat upload',
    'invoice.btnApprove': 'Approve',
    'invoice.btnReject': 'Reject',
    'invoice.btnSendBack': 'Send Back',
    'invoice.btnAudit': 'Audit',

    // ── Entertainment ──
    'entertain.tabList': 'Daftar Entertainment',
    'entertain.tabSettle': 'Penyelesaian / Settle',
    'entertain.entryType': 'Tipe Entry',
    'entertain.saveDraft': 'Simpan ke Draft',
    'entertain.settle': 'Settle',
    'entertain.saving': 'Menyimpan...',
    'entertain.settling': 'Settling...',
    'entertain.closeForm': 'Tutup Form',
    'entertain.addNew': 'Tambah Baru',
    'entertain.addRule': 'Tambah Rule',
    'entertain.closeRule': 'Tutup',
    'entertain.reimburseNote': 'Entry tipe Reimburse langsung ke settle tanpa perlu pengajuan. Semua field wajib diisi.',
    'entertain.placeGL': 'Isi No GL',
    'entertain.selectBusinessType': 'Pilih Jenis Usaha',
    'entertain.listTitle': 'Daftar Entertainment Expenses',
    'entertain.settleTitle': 'Penyelesaian / Settle',
    'entertain.ruleRequired': 'Nama rule dan target wajib diisi',
    'entertain.ruleSaved': 'Rule berhasil disimpan',
    'entertain.ruleDeleted': 'Rule berhasil dihapus',
    'entertain.dataDeleted': 'Data berhasil dihapus',
    'entertain.dataUpdated': 'Data berhasil diupdate',
    'entertain.settledSuccess': 'Berhasil di-settle',
    'entertain.settledUpdated': 'Data diupdate dan berhasil di-settle',
    'entertain.gagalLoad': 'Gagal memuat data',
    'entertain.gagalSettle': 'Gagal settle',
    'entertain.gagalSave': 'Gagal menyimpan',
    'entertain.fieldRequired': 'Harap isi semua field yang wajib',
    'entertain.placeRequired': 'Tempat wajib diisi',
    'entertain.addressRequired': 'Alamat wajib diisi',
    'entertain.jenisRequired': 'Jenis wajib diisi',
    'entertain.customJenisRequired': 'Custom jenis wajib diisi',
    'entertain.noAFRequired': 'No AF wajib diisi',
    'entertain.noAFFormat': 'No AF harus format PR diikuti 6 digit (contoh: PR000001)',
    'entertain.noGLRequired': 'No GL wajib diisi',
    'entertain.relasiRequired': 'Minimal 1 relasi wajib diisi',
    'entertain.jenisUsahaRequired': 'Jenis Usaha wajib diisi',
    'entertain.customJenisUsahaRequired': 'Custom jenis usaha wajib diisi',
    'entertain.lampiranRequired': 'Minimal 1 lampiran wajib diupload',
    'entertain.fileAttached': 'file ditempel ke lampiran',
    'entertain.unsettledWarning': 'Selesaikan semua entry yang belum settle sebelum membuat entry baru.',
    'entertain.unsettledFirst': 'Selesaikan semua entry yang belum settle dulu',
    'entertain.unsettledCount': 'Terdapat entry yang belum settle',
    'entertain.entriesNotSettled': 'Entry yang belum settle',
    'entertain.settleFirstMsg': 'Semua entry harus berstatus "Settled" terlebih dahulu sebelum dapat membuat entry baru.',
    'entertain.duplicateDetected': 'Data anomali terdeteksi:',
    'entertain.duplicateBy': 'oleh',
    'entertain.settleAmountRequired': 'Settle amount wajib diisi',
    'entertain.gagalLoadRules': 'Gagal memuat rules',

    // ── AnyDoc ──
    'anydoc.subtitle': 'Konversi dokumen apa pun menjadi Markdown bersih — didukung mesin Rust Firecrawl',
    'anydoc.engineActive': 'Mesin aktif',

    // ── AI PDF Tools ──
    'aipdf.hapusTtd': 'Hapus tanda tangan',
    'aipdf.hapusTemplate': 'Hapus template',
    'aipdf.privacyHint': 'Hanya pembuat (atau admin) yang bisa melihat',
    'aipdf.viewOcrText': 'Lihat teks hasil OCR',
    'aipdf.shareDept': 'Bagikan ke departemen lain',
    'aipdf.deleteHistory': 'Hapus riwayat ini',
    'aipdf.templateHint': 'Template <b>NR</b> (1 ttd: ttd.png menimpa "Kaoru Nomura") dan <b>DM</b> (2 ttd: + agnes.png di atas "Agnestachia") sudah otomatis siap pakai — tinggal unggah PDF & proses.',

    // ── TaxCalculation ──
    'taxcalc.downloadTemplateMaster': 'Download Template Master Objek Pajak',
    'taxcalc.importMaster': 'Import Master Objek Pajak',
    'taxcalc.calcTitle': 'Perhitungan Pajak',
    'taxcalc.bukanPegawaiTip': 'Aktifkan perhitungan PPh 21 Bukan Pegawai (50% Bruto - Progresif)',
    'taxcalc.copyNilai': 'Copy Nilai Angka',

    // ── TaxSummary ──
    'taxsum.copyTotal': 'Salin Total',
    'taxsum.copy': 'Salin',
    'taxsum.renameColumn': 'Ubah Nama',
    'taxsum.deleteColumn': 'Hapus Kolom',
    'taxsum.downloadTemplatePPh': 'Download Template PPh',
    'taxsum.downloadTemplatePPN': 'Download Template PPN',

    // ── MasterData ──
    'master.downloadTemplate': 'Download template Excel untuk import users',
    'master.importUsers': 'Import users dari file Excel',

    // ── Documents ──
    'doc.zoomDetail': 'Zoom Detail',

    // ── TaxMonitoring ──
    'taxmon.detail': 'Detail',
    'taxmon.edit': 'Edit',

    // ── Inventory ──
    'inv.viewDetail': 'Lihat Detail',
    'inv.restoreGudang': 'Restore ke Gudang',

    // ── Modals ──
    'modal.taxUpload': 'Upload Dokumen Pemeriksaan',
    'modal.taxFileDetail': 'Detail Dokumen & OCR',
    'modal.externalTransfer': 'Kirim ke Indoarsip',

    // ── Components ──
    'comp.mapHeader': 'Map sebagai field header',
    'comp.tableHeader': 'Jadikan header tabel item',
    'comp.groupCol': 'Kolom grup: nilai ada di baris di atas baris data dan diwariskan ke baris di bawah',
    'comp.privacyHint': 'Hanya pembuat (atau admin) yang bisa melihat',
    'comp.downloadPdf': 'Unduh PDF asli',
    'comp.reExtract': 'Ekstrak ulang tanpa upload',
    'comp.shareDept': 'Bagikan ke departemen lain',
    'comp.deleteFromArsip': 'Hapus dari arsip',
    'comp.downloadExcel': 'Unduh ulang Excel ini (tanpa extract ulang)',
    'comp.deleteHistory': 'Hapus history export ini',

    // ── Options / Filter ──
    'opt.allDealer': 'Semua Dealer',
    'opt.allStatus': 'Semua Status',
    'opt.all': 'Semua',
    'opt.invoice': 'Invoice',
    'opt.proforma': 'Proforma',
    'opt.user': 'User',
    'opt.role': 'Role',
    'opt.division': 'Divisi',
    'opt.selectUser': '— Pilih user —',
    'opt.selectRole': '— Pilih role —',
    'opt.selectDivision': '— Pilih divisi —',
    'opt.selectSomething': 'Pilih',
    'opt.dp': 'DP (Down Payment)',
    'opt.pelunasan': 'Pelunasan (Settlement)',
    'opt.selectPoDp': '-- Pilih PO DP --',
    'opt.nihil': 'Nihil',
    'opt.reimburse': 'Reimburse',
    'opt.plan': 'Plan',
    'opt.selectSignature': '— pilih tanda tangan —',
    'opt.loadingLanguages': 'Memuat daftar bahasa…',
    'opt.noLanguages': 'Bahasa tidak tersedia',
    'opt.autoDetect': '✨ Auto — deteksi otomatis',
    'opt.manualSelect': '────── pilih manual ──────',
    'opt.posBottomLeft': 'Kiri bawah',
    'opt.posBottomCenter': 'Tengah bawah',
    'opt.posBottomRight': 'Kanan bawah',
    'opt.posTopLeft': 'Kiri atas',
    'opt.posTopCenter': 'Tengah atas',
    'opt.posTopRight': 'Kanan atas',
    'opt.alignLeft': 'Kiri',
    'opt.alignCenter': 'Tengah',
    'opt.alignRight': 'Kanan',
    'opt.aboveName': 'Di atas nama',
    'opt.coverName': 'Menimpa nama & jabatan',
    'opt.regexPattern': 'Pola Regex',
    'theVision': 'The Vision',
    'opt.finance': 'Finance',
    'opt.hr': 'HR',
    'opt.it': 'IT',
    'opt.audit': 'Audit',

    // ── Status Map ──
    'status.submitted': 'Submitted',
    'status.draft': 'Draft',
    'status.sentBack': 'Dikembalikan',
    'status.rejected': 'Ditolak',
    'status.approved': 'Disetujui',
    'status.pending': 'Pending',
    'status.cancelled': 'Dibatalkan',
    'status.settled': 'Selesai',

    // ── Invoice Help Text ──
    'invoice.emptyData': 'Tidak ada data invoice',
    'invoice.delReplaceWarning': 'Invoice pengganti akan dihapus permanen beserta item barangnya.',
    'invoice.pelunasanOther': 'Pelunasan lain:',
    'invoice.pelunasanHelp': 'Daftar barang pelunasan harus sama dengan full amount DP. Amount pelunasan diisi di field "Uang Masuk (Pelunasan)".',
    'invoice.dpHelp': 'Masukkan total nilai penuh (full amount). Daftar barang harus berjumlah sama dengan full amount. DP diisi di field "Uang Masuk (DP)".',
    'invoice.refPoDp': 'Referensi PO DP (Pelunasan) *',
    'invoice.uangMasukPelunasan': 'Uang Masuk (Pelunasan) *',
    'invoice.uangMasukDP': 'Uang Masuk (DP) *',
    'invoice.pelunasanToPay': 'Pelunasan yang harus dibayar',
    'invoice.chartUangMasuk': 'Uang Masuk',

    // ── AI PDF Tools ──
    'aipdf.templateReady': 'Template siap. Cukup: 1) unggah file PDF di atas → 2) klik Pratinjau Deteksi Blok (opsional) → 3) klik Proses Tanda Tangan PDF. Tidak perlu atur apa pun lagi.',
    'aipdf.fixedModeHint': 'Mode ini menempatkan ttd di posisi tetap untuk semua halaman terpilih — gunakan Template Otomatis agar ttd ditempatkan otomatis di posisi nama & hanya di halaman yang ada namanya.',
    'aipdf.signatureMode': 'Mode Tanda Tangan',
    'aipdf.position': 'Posisi',
    'aipdf.alignment': 'Penyelarasan',
    'aipdf.signatureType': 'Tipe Tanda Tangan',

    // ── SopFlow ──
    'sop.defaultCategory': 'Default Kategori',

    // ── Documents ──
    'doc.filterAll': 'Semua',

    // ── MasterData ──
    'master.noModel': 'Tidak ada model',

    // ── AiChatAssistant ──
    'chat.resetSession': 'Mulai Awal',
    // ── More Options ──
    'opt.selectMonth': '- Pilih Bulan -',
    'opt.selectDept': '- Pilih Dept -',
    'opt.selectSlot': '-- Pilih Slot Kosong --',
    'opt.loadingModel': 'Memuat model...',
    'opt.labelSameLine': 'Label → nilai (baris sama)',
    'opt.labelNextLine': 'Label → baris berikutnya',
    'opt.labelAnchor': 'Label di bagian (anchor)',
    'opt.regexPattern': 'Pola Regex',
    'theVision': 'The Vision',


    // ── Dashboard ──
    'dash.month': 'Bulan',
    'dash.year': 'Tahun',
    'dash.quarter': 'Kuartal',
    'dash.all': 'Semua',
  },
  en: {
    'language.id': 'ID',
    'language.en': 'EN',

    'sidebar.category.general': 'GENERAL',
    'sidebar.category.document': 'DOCUMENT',
    'sidebar.category.tax': 'TAX & COMPLIANCE',
    'sidebar.category.system': 'SYSTEM',
    'sidebar.category.accounting': 'ACCOUNTING',

    'sidebar.item.dashboard': 'Dashboard',
    'sidebar.item.myJob': 'My Job',
    'sidebar.item.manualBook': 'Manual Book',
    'sidebar.item.sop': 'SOP',
    'sidebar.item.filling': 'Filling',
    'sidebar.item.documents': 'Documents',
    'sidebar.item.anydoc': 'AnyDoc Converter',
    'sidebar.item.aiDocIntel': 'AI Document Intelligence',
    'sidebar.item.aiDocTrain': 'Document Training',
    'sidebar.item.aiPdfTools': 'AI PDF Tools',
    'sidebar.item.approvals': 'Entertainment Expenses',
    'sidebar.item.entertainment': 'Entertainment',
    'sidebar.item.invoices': 'Invoices',
    'sidebar.item.forwarder': 'Forwarder',
    'sidebar.item.pdfTemplates': 'PDF Templates',
    'sidebar.item.compliance': 'Compliance',
    'sidebar.item.taxCalc': 'Tax Calc',
    'sidebar.item.reporting': 'Reporting',
    'sidebar.item.masterData': 'Master Data',
    'sidebar.item.book': 'Book (COA)',
    'sidebar.item.systemLogs': 'System Logs',

    'sidebar.ocr.ready': 'OCR Ready',
    'sidebar.ocr.queueEmpty': 'Queue is empty',
    'sidebar.ocr.processing': 'OCR Processing...',
    'sidebar.ocr.active': 'Active',
    'sidebar.ocr.waiting': 'Queued',
    'sidebar.ocr.ok': 'Done',
    'sidebar.ocr.fail': 'Failed',
    'sidebar.ocr.reset': 'Reset',

    'sidebar.user.guest': 'Guest',
    'sidebar.user.viewer': 'Viewer',
    'sidebar.search.placeholder': 'Search menu…',
    'sidebar.search.empty': 'No menu found',
    'sidebar.search.results': 'Search Results',
    'sidebar.action.toggleTheme': 'Toggle Theme',
    'sidebar.action.logout': 'Logout',

    // ── Common UI ──
    'common.previous': 'Previous',
    'common.next': 'Next',
    'common.search': 'Search',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.add': 'Add',
    'common.close': 'Close',
    'common.loading': 'Loading...',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.refresh': 'Refresh',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.confirm': 'Confirm',
    'common.success': 'Success',
    'common.error': 'Error',
    'common.warning': 'Warning',
    'common.noData': 'No data',
    'common.all': 'All',
    'common.status': 'Status',
    'common.type': 'Type',
    'common.name': 'Name',
    'common.description': 'Description',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.total': 'Total',
    'common.action': 'Action',
    'common.copy': 'Copy',
    'common.copied': 'Copied!',
    'common.detail': 'Detail',
    'common.back': 'Back',
    'common.submit': 'Submit',
    'common.filter': 'Filter',
    'common.sort': 'Sort',
    'common.of': 'of',
    'common.page': 'Page',
    'common.rows': 'rows',
    'common.selectAll': 'Select All',
    'common.selected': 'selected',
    'common.upload': 'Upload',
    'common.download': 'Download',
    'common.print': 'Print',
    'common.copyClipboard': 'Copy to clipboard',
    'common.preview': 'Preview',
    'common.reset': 'Reset',
    'common.apply': 'Apply',
    'common.enabled': 'Enabled',
    'common.disabled': 'Disabled',
    'common.active': 'Active',
    'common.inactive': 'Inactive',

    // ── Tooltips ──
    'tooltip.exportExcel': 'Export all data to Excel',
    'tooltip.importData': 'Import data from Excel file',
    'tooltip.downloadTemplate': 'Download Excel template for import',
    'tooltip.deleteEntry': 'Delete this entry',
    'tooltip.editEntry': 'Edit this entry',
    'tooltip.viewDetail': 'View detail',
    'tooltip.refresh': 'Refresh data',
    'tooltip.history': 'View history',
    'tooltip.shareDept': 'Share to other departments',
    'tooltip.downloadPdf': 'Download original PDF',
    'tooltip.ocrView': 'View OCR text',
    'tooltip.zoomDetail': 'Zoom Detail',
    'tooltip.usePpnCustom': 'Use custom PPN',
    'tooltip.collapseGroup': 'Group column: value is in the row above data and inherited to rows below',
    'tooltip.mapHeader': 'Map as header field',
    'tooltip.tableHeader': 'Set as item table header',
    'tooltip.copyValue': 'Copy Value',
    'tooltip.copyTotal': 'Copy Total',
    'tooltip.renameColumn': 'Rename',
    'tooltip.deleteColumn': 'Delete Column',
    'tooltip.restoreGudang': 'Restore to Warehouse',
    'tooltip.logout': 'Logout',
    'tooltip.previous': 'Previous',
    'tooltip.next': 'Next',

    // ── Months ──
    'month.jan': 'January', 'month.feb': 'February', 'month.mar': 'March',
    'month.apr': 'April', 'month.may': 'May', 'month.jun': 'June',
    'month.jul': 'July', 'month.aug': 'August', 'month.sep': 'September',
    'month.oct': 'October', 'month.nov': 'November', 'month.dec': 'December',

    // ── Invoices ──
    'invoice.status.submitted': 'Submitted',
    'invoice.status.proforma': 'Proforma',
    'invoice.status.pending': 'Pending',
    'invoice.status.sentBack': 'Sent Back',
    'invoice.status.rejected': 'Rejected',
    'invoice.status.approved': 'Approved',
    'invoice.status.taxRequested': 'Tax Requested',
    'invoice.status.tax': 'Tax',
    'invoice.status.settled': 'Settled',
    'invoice.status.cancelled': 'Cancelled',
    'invoice.stepper.submit': 'Submit',
    'invoice.stepper.proforma': 'Proforma',
    'invoice.stepper.tax': 'Tax',
    'invoice.stepper.settle': 'Settle',
    'invoice.searchPlaceholder': 'Search (PO, proforma, dealer...)',
    'invoice.searchData': 'Search data...',
    'invoice.searchInvoice': 'Search invoice no / PO / dealer...',
    'invoice.searchDealer': 'Search Dealer...',
    'invoice.searchModel': 'Search Model...',
    'invoice.placeNPWP': 'NPWP (16 digits)',
    'invoice.placeDealerName': 'Dealer Name',
    'invoice.placeAddress': 'Address',
    'invoice.placeModel': 'Model / Item Code',
    'invoice.placeItemDesc': 'Item Description',
    'invoice.placePrice': 'Price',
    'invoice.placeExample': 'Example: Approval Accounting',
    'invoice.placeEmail': 'Type email, separate with comma / enter. Example: accounting@company.com',
    'invoice.placeNoInvoice': 'Invoice No.',
    'invoice.exportAll': 'Export all invoice data to Excel',
    'invoice.usePpnCustom': 'Use custom PPN',
    'invoice.errorUpload': 'Upload error',
    'invoice.btnApprove': 'Approve',
    'invoice.btnReject': 'Reject',
    'invoice.btnSendBack': 'Send Back',
    'invoice.btnAudit': 'Audit',

    // ── Entertainment ──
    'entertain.tabList': 'Entertainment List',
    'entertain.tabSettle': 'Settlement',
    'entertain.entryType': 'Entry Type',
    'entertain.saveDraft': 'Save to Draft',
    'entertain.settle': 'Settle',
    'entertain.saving': 'Saving...',
    'entertain.settling': 'Settling...',
    'entertain.closeForm': 'Close Form',
    'entertain.addNew': 'Add New',
    'entertain.addRule': 'Add Rule',
    'entertain.closeRule': 'Close',
    'entertain.reimburseNote': 'Reimburse entries go directly to settle — no approval needed. All fields are required.',
    'entertain.placeGL': 'Enter GL number',
    'entertain.selectBusinessType': 'Select Business Type',
    'entertain.listTitle': 'Entertainment Expenses List',
    'entertain.settleTitle': 'Settlement',
    'entertain.ruleRequired': 'Rule name and target are required',
    'entertain.ruleSaved': 'Rule saved successfully',
    'entertain.ruleDeleted': 'Rule deleted successfully',
    'entertain.dataDeleted': 'Data deleted successfully',
    'entertain.dataUpdated': 'Data updated successfully',
    'entertain.settledSuccess': 'Settled successfully',
    'entertain.settledUpdated': 'Data updated and settled successfully',
    'entertain.gagalLoad': 'Failed to load data',
    'entertain.gagalSettle': 'Settle failed',
    'entertain.gagalSave': 'Failed to save',
    'entertain.fieldRequired': 'Please fill all required fields',
    'entertain.placeRequired': 'Venue is required',
    'entertain.addressRequired': 'Address is required',
    'entertain.jenisRequired': 'Type is required',
    'entertain.customJenisRequired': 'Custom type is required',
    'entertain.noAFRequired': 'AF Number is required',
    'entertain.noAFFormat': 'AF Number must be PR followed by 6 digits (e.g. PR000001)',
    'entertain.noGLRequired': 'GL Number is required',
    'entertain.relasiRequired': 'At least 1 relation is required',
    'entertain.jenisUsahaRequired': 'Business type is required',
    'entertain.customJenisUsahaRequired': 'Custom business type is required',
    'entertain.lampiranRequired': 'At least 1 attachment is required',
    'entertain.fileAttached': 'files attached',
    'entertain.unsettledWarning': 'Settle all pending entries before creating a new one.',
    'entertain.unsettledFirst': 'Settle all pending entries first',
    'entertain.unsettledCount': 'There are unsettled entries',
    'entertain.entriesNotSettled': 'Entries not yet settled',
    'entertain.settleFirstMsg': 'All entries must be "Settled" before creating a new entry.',
    'entertain.duplicateDetected': 'Potential duplicate data detected:',
    'entertain.duplicateBy': 'by',
    'entertain.settleAmountRequired': 'Settle amount is required',
    'entertain.gagalLoadRules': 'Failed to load rules',

    // ── AnyDoc ──
    'anydoc.subtitle': 'Convert any document to clean Markdown — powered by Rust Firecrawl engine',
    'anydoc.engineActive': 'Engine active',

    // ── AI PDF Tools ──
    'aipdf.hapusTtd': 'Delete signature',
    'aipdf.hapusTemplate': 'Delete template',
    'aipdf.privacyHint': 'Only creator (or admin) can view',
    'aipdf.viewOcrText': 'View OCR text',
    'aipdf.shareDept': 'Share to other departments',
    'aipdf.deleteHistory': 'Delete this history',
    'aipdf.templateHint': 'Template <b>NR</b> (1 signature: ttd.png overwrites "Kaoru Nomura") and <b>DM</b> (2 signatures: + agnes.png above "Agnestachia") are auto-ready — just upload PDF & process.',

    // ── TaxCalculation ──
    'taxcalc.downloadTemplateMaster': 'Download Master Tax Object Template',
    'taxcalc.importMaster': 'Import Master Tax Objects',
    'taxcalc.calcTitle': 'Tax Calculation',
    'taxcalc.bukanPegawaiTip': 'Enable Non-Employee PPh 21 Calculation (50% Gross - Progressive)',
    'taxcalc.copyNilai': 'Copy Numeric Value',

    // ── TaxSummary ──
    'taxsum.copyTotal': 'Copy Total',
    'taxsum.copy': 'Copy',
    'taxsum.renameColumn': 'Rename',
    'taxsum.deleteColumn': 'Delete Column',
    'taxsum.downloadTemplatePPh': 'Download PPh Template',
    'taxsum.downloadTemplatePPN': 'Download PPN Template',

    // ── MasterData ──
    'master.downloadTemplate': 'Download Excel template for user import',
    'master.importUsers': 'Import users from Excel file',

    // ── Documents ──
    'doc.zoomDetail': 'Zoom Detail',

    // ── TaxMonitoring ──
    'taxmon.detail': 'Detail',
    'taxmon.edit': 'Edit',

    // ── Inventory ──
    'inv.viewDetail': 'View Detail',
    'inv.restoreGudang': 'Restore to Warehouse',

    // ── Modals ──
    'modal.taxUpload': 'Upload Inspection Document',
    'modal.taxFileDetail': 'Document Detail & OCR',
    'modal.externalTransfer': 'Send to Indoarsip',

    // ── Components ──
    'comp.mapHeader': 'Map as header field',
    'comp.tableHeader': 'Set as item table header',
    'comp.groupCol': 'Group column: value is in the row above data and inherited to rows below',
    'comp.privacyHint': 'Only creator (or admin) can view',
    'comp.downloadPdf': 'Download original PDF',
    'comp.reExtract': 'Re-extract without upload',
    'comp.shareDept': 'Share to other departments',
    'comp.deleteFromArsip': 'Delete from archive',
    'comp.downloadExcel': 'Re-download this Excel (without re-extract)',
    'comp.deleteHistory': 'Delete this export history',

    // ── Options / Filter ──
    'opt.allDealer': 'All Dealers',
    'opt.allStatus': 'All Status',
    'opt.all': 'All',
    'opt.invoice': 'Invoice',
    'opt.proforma': 'Proforma',
    'opt.user': 'User',
    'opt.role': 'Role',
    'opt.division': 'Division',
    'opt.selectUser': '— Select user —',
    'opt.selectRole': '— Select role —',
    'opt.selectDivision': '— Select division —',
    'opt.selectSomething': 'Select',
    'opt.dp': 'DP (Down Payment)',
    'opt.pelunasan': 'Pelunasan (Settlement)',
    'opt.selectPoDp': '-- Select PO DP --',
    'opt.nihil': 'Nihil',
    'opt.reimburse': 'Reimburse',
    'opt.plan': 'Plan',
    'opt.selectSignature': '— select signature —',
    'opt.loadingLanguages': 'Loading languages…',
    'opt.noLanguages': 'Languages not available',
    'opt.autoDetect': '✨ Auto — auto detect',
    'opt.manualSelect': '────── select manually ──────',
    'opt.posBottomLeft': 'Bottom left',
    'opt.posBottomCenter': 'Bottom center',
    'opt.posBottomRight': 'Bottom right',
    'opt.posTopLeft': 'Top left',
    'opt.posTopCenter': 'Top center',
    'opt.posTopRight': 'Top right',
    'opt.alignLeft': 'Left',
    'opt.alignCenter': 'Center',
    'opt.alignRight': 'Right',
    'opt.aboveName': 'Above name',
    'opt.coverName': 'Cover name & title',
    'opt.regexPattern': 'Regex Pattern',
    'theVision': 'The Vision',
    'opt.finance': 'Finance',
    'opt.hr': 'HR',
    'opt.it': 'IT',
    'opt.audit': 'Audit',

    // ── Status Map ──
    'status.submitted': 'Submitted',
    'status.draft': 'Draft',
    'status.sentBack': 'Sent Back',
    'status.rejected': 'Rejected',
    'status.approved': 'Approved',
    'status.pending': 'Pending',
    'status.cancelled': 'Cancelled',
    'status.settled': 'Settled',

    // ── Invoice Help Text ──
    'invoice.emptyData': 'No invoice data',
    'invoice.delReplaceWarning': 'Replacement invoice will be permanently deleted with all its items.',
    'invoice.pelunasanOther': 'Other settlement:',
    'invoice.pelunasanHelp': 'Settlement item list must match the full DP amount. Settlement amount is filled in the "Incoming Funds (Settlement)" field.',
    'invoice.dpHelp': 'Enter the total full amount. Item list must equal the full amount. DP is filled in the "Incoming Funds (DP)" field.',
    'invoice.refPoDp': 'PO DP Reference (Settlement) *',
    'invoice.uangMasukPelunasan': 'Incoming Funds (Settlement) *',
    'invoice.uangMasukDP': 'Incoming Funds (DP) *',
    'invoice.pelunasanToPay': 'Settlement amount to pay',
    'invoice.chartUangMasuk': 'Incoming Funds',

    // ── AI PDF Tools ──
    'aipdf.templateReady': 'Template ready. Simply: 1) upload PDF above → 2) click Block Detection Preview (optional) → 3) click Process PDF Signature. No further settings needed.',
    'aipdf.fixedModeHint': 'This mode places signatures in a fixed position for all selected pages — use Auto Template for signatures to be placed automatically at name positions & only on pages that have the name.',
    'aipdf.signatureMode': 'Signature Mode',
    'aipdf.position': 'Position',
    'aipdf.alignment': 'Alignment',
    'aipdf.signatureType': 'Signature Type',

    // ── SopFlow ──
    'sop.defaultCategory': 'Default Category',

    // ── Documents ──
    'doc.filterAll': 'All',

    // ── MasterData ──
    'master.noModel': 'No model available',

    // ── AiChatAssistant ──
    'chat.resetSession': 'Start Over',
    // ── More Options ──
    'opt.selectMonth': '- Select Month -',
    'opt.selectDept': '- Select Dept -',
    'opt.selectSlot': '-- Select Empty Slot --',
    'opt.loadingModel': 'Loading models...',
    'opt.labelSameLine': 'Label → value (same line)',
    'opt.labelNextLine': 'Label → next line',
    'opt.labelAnchor': 'Label in section (anchor)',
    'opt.regexPattern': 'Regex Pattern',
    'theVision': 'The Vision',


    // ── Dashboard ──
    'dash.month': 'Month',
    'dash.year': 'Year',
    'dash.quarter': 'Quarter',
    'dash.all': 'All',
  },
};

const LanguageContext = createContext(null);

const pickInitialLanguage = () => {
  if (typeof window === 'undefined') return 'id';
  const stored = localStorage.getItem(LANGUAGE_STORAGE_KEY);
  if (stored === 'id' || stored === 'en') return stored;
  const preferred = navigator.language?.toLowerCase() || 'id';
  return preferred.startsWith('en') ? 'en' : 'id';
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(pickInitialLanguage);

  useEffect(() => {
    if (typeof window !== 'undefined') {
      localStorage.setItem(LANGUAGE_STORAGE_KEY, language);
    }
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language;
    }
  }, [language]);

  const value = useMemo(() => {
    const t = (key, fallback = key) => translations[language]?.[key] ?? fallback;
    return {
      language,
      setLanguage,
      t,
      isEnglish: language === 'en',
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return context;
}
